site_name: ""
site_url: "https://govhub.github.io/govhub/"
site_author: Lab Livre
site_description: >-
  Gov Hub - plataforma livre de integração de dados e informações governamentais - Explore como a gestão orientada a dados pode transformar a administração pública, 
  integrando e qualificando dados de sistemas estruturantes essenciais. 
  Este projeto aborda os desafios da fragmentação e inconsistência de dados, promovendo eficiência, 
  transparência e melhor tomada de decisão no âmbito governamental.

# Repository
repo_name: GovHub-br/govhub
repo_url: https://github.com/GovHub-br/govhub
repo_branch: main
edit_uri: edit/main/docs/

# Copyright
copyright: Lab Livre 2025

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: purple
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: Inter
    code: 'JetBrains Mono'
  favicon: assets/favicon-96x96.png
  logo: assets/logo.svg
  language: pt-BR

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"\`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      pagination_per_page: 10
      archive_toc: true
      categories_toc: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GovHub-br/govhub.githubio

# Custom CSS for Inter font and footer styling
extra_css:
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap
  - assets/custom-footer.css
  - assets/pdf-viewer.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Sobre: home.md
  - E-book:
    - Gov Hub - plataforma livre de integração de dados e informações governamentais: ebook.md
  - Sobre o Projeto:
    - Visão geral: sobre-projeto/overview.md
    - Sistemas Estruturantes: sobre-projeto/sistemas-estruturantes.md
    - Gestão Orientada a Dados: sobre-projeto/gestao-dados.md
    - Replicação: sobre-projeto/replicacao.md
    - Equipe: sobre-projeto/equipe.md
  - Documentação:
    - Instalação: documentacao/instalacao.md
    - Arquitetura: documentacao/arquitetura.md
    - Tutoriais: 
      - Infraestrutura: 
        - CI/CD: documentacao/tutoriais/infraestrutura/cicd.md
        - Docker: documentacao/tutoriais/infraestrutura/docker.md
        - Kubernetes: documentacao/tutoriais/infraestrutura/kubernetes.md
        - Jupyter: documentacao/tutoriais/infraestrutura/jupyter.md
        - Airflow: documentacao/tutoriais/infraestrutura/airflow.md
        - PostgreSQL: documentacao/tutoriais/infraestrutura/postgresql.md
      - DBT: 
        - Modelos: documentacao/tutoriais/dbt/modelos.md
        - Arquitetura medallion: documentacao/tutoriais/dbt/arquitetura-medallion.md
        - Astronomer Cosmos: documentacao/tutoriais/dbt/cosmos.md
        - Testes: documentacao/tutoriais/dbt/testes.md
        - Macros: documentacao/tutoriais/dbt/macros.md
        - Snaphots: documentacao/tutoriais/dbt/snapshots.md
        - DBT Docs: documentacao/tutoriais/dbt/dbt-docs.md
      - Superset: 
        - Conexões: documentacao/tutoriais/superset/conexoes.md
        - Criando uma visualização: documentacao/tutoriais/superset/criando-chart.md
        - Criando um dashboard: documentacao/tutoriais/superset/criando-dashboard.md
        - Importando e exportando dashboards: documentacao/tutoriais/superset/import-export.md
      - Sistemas estruturantes: 
        - DAG de ingestão: documentacao/tutoriais/sistemas-estruturantes/sistemas-estruturantes.md
        - Guia de sistemas: documentacao/tutoriais/sistemas-estruturantes/importar_bancos.md
  - Comunidade: 
    - Guia de Contribuição: comunidade/guia-contribuicao.md
    - Licença: comunidade/licenca.md
    - Dashboards Templates: comunidade/dashboards-templates.md
    - Pré-requisitos: comunidade/pre-requisitos.md
  - Publicações: 
      - Blog: blog/index.md
      - Ver Todas: land/dist/publicacoes.html
