sonar.organization=govhub-br
sonar.projectKey=GovHub-br_gov-bricks

sonar.sources=airflow
sonar.tests=tests

sonar.exclusions=**/*.sql
sonar.coverage.exclusions=**/*.sql
sonar.cpd.exclusions=**/*.sql,tests/**
