blank_issues_enabled: false   # desabilita "Open a blank issue" e força escolher um template
contact_links:
  - name: Dúvidas gerais
    url: https://github.com/SEU_USUARIO/SEU_REPO/discussions
    about: Use Discussions para perguntas que não são bug/feature.
