name: Feature request
description: Sugira uma nova funcionalidade
labels: ["enhancement"]
title: "[Feat]: "
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivação
      description: Qual problema essa ideia resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Descreva a solução ideal.
      placeholder: Fluxo, APIs, telas...
