govhub:
  name: Equipe GovHub
  description: >
    Equipe de desenvolvimento e pesquisa do GovHub - Plataforma de dados públicos
    desenvolvida pelo Lab Livre da UnB em parceria com IPEA.
  avatar: https://github.com/govhub-br.png
  url: https://govhub.br
