"""Configuração das tabelas do SICONV para a ingestão unificada.

Migrado de data-application-mir (``airflow_lappis/plugins/tabelas_siconv.py``,
DAG ``airflow_lappis/dags/data_ingest/siconv/mir/sincov_ingest_dag.py``).

O zip nacional (``ClienteSiconv.URL_ZIP``) traz 16 CSVs, um por entidade, sem
nenhum filtro de órgão — por isso a ingestão vive em ``data_ingest/siconv/``,
sem subpasta de órgão (ADR-0004), como o PPA.

``primary_key`` é a chave natural de cada entidade, usada por
``landing_zone.write_raw`` para fazer upsert (via ``ON CONFLICT``) na zona raw
quando o backend é ``warehouse``. 4 das 16 entidades (``desbloqueio``,
``prorroga_oficio``, ``empenho``, ``historico_situacao``) não têm um
identificador de linha único de verdade na fonte, mas têm uma combinação de
colunas estável o bastante para servir de chave composta — achada pelo
repositório antigo depois da migração inicial deste arquivo (antes disso,
essas 4 entidades ficavam com ``primary_key`` vazio). Continuam com
``truncate_before_insert: True``: a DAG esvazia a tabela raw
(``landing_zone.truncate_raw_warehouse``) antes da primeira carga da
execução — full-refresh, não incremental — porque a fonte não confirma se um
registro ausente do zip de hoje foi excluído ou só não mudou.
"""

from typing import List, NotRequired, TypedDict


class TabelaSiconv(TypedDict):
    nome_tabela: str
    nome_csv: str
    primary_key: List[str]
    skip_rows: int
    colunas: List[str]
    truncate_before_insert: NotRequired[bool]


TABELAS_SICONV: List[TabelaSiconv] = [
    {
        "nome_tabela": "proposta",
        "nome_csv": "siconv_proposta.csv",
        "primary_key": ["id_proposta"],
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA",
            "UF_PROPONENTE",
            "MUNIC_PROPONENTE",
            "COD_MUNIC_IBGE",
            "COD_ORGAO_SUP",
            "DESC_ORGAO_SUP",
            "NATUREZA_JURIDICA",
            "NR_PROPOSTA",
            "DIA_PROP",
            "MES_PROP",
            "ANO_PROP",
            "DIA_PROPOSTA",
            "COD_ORGAO",
            "DESC_ORGAO",
            "MODALIDADE",
            "IDENTIF_PROPONENTE",
            "NM_PROPONENTE",
            "CEP_PROPONENTE",
            "ENDERECO_PROPONENTE",
            "BAIRRO_PROPONENTE",
            "NM_BANCO",
            "SITUACAO_CONTA",
            "SITUACAO_PROJETO_BASICO",
            "SIT_PROPOSTA",
            "DIA_INIC_VIGENCIA_PROPOSTA",
            "DIA_FIM_VIGENCIA_PROPOSTA",
            "OBJETO_PROPOSTA",
            "ITEM_INVESTIMENTO",
            "ENVIADA_MANDATARIA",
            "NOME_SUBTIPO_PROPOSTA",
            "DESCRICAO_SUBTIPO_PROPOSTA",
            "VL_GLOBAL_PROP",
            "VL_REPASSE_PROP",
            "VL_CONTRAPARTIDA_PROP",
            "CD_AGENCIA",
            "CD_CONTA",
        ],
    },
    {
        "nome_tabela": "convenio",
        "nome_csv": "siconv_convenio.csv",
        "primary_key": ["nr_convenio"],
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "ID_PROPOSTA",
            "DIA",
            "MES",
            "ANO",
            "DIA_ASSIN_CONV",
            "SIT_CONVENIO",
            "SUBSITUACAO_CONV",
            "SITUACAO_PUBLICACAO",
            "INSTRUMENTO_ATIVO",
            "IND_OPERA_OBTV",
            "NR_PROCESSO",
            "UG_EMITENTE",
            "DIA_PUBL_CONV",
            "DIA_INIC_VIGENC_CONV",
            "DIA_FIM_VIGENC_CONV",
            "DIA_FIM_VIGENC_ORIGINAL_CONV",
            "DIAS_PREST_CONTAS",
            "DIA_LIMITE_PREST_CONTAS",
            "DATA_SUSPENSIVA",
            "DATA_RETIRADA_SUSPENSIVA",
            "DIAS_CLAUSULA_SUSPENSIVA",
            "SITUACAO_CONTRATACAO",
            "IND_ASSINADO",
            "MOTIVO_SUSPENSAO",
            "IND_FOTO",
            "QTDE_CONVENIOS",
            "QTD_TA",
            "QTD_PRORROGA",
            "VL_GLOBAL_CONV",
            "VL_REPASSE_CONV",
            "VL_CONTRAPARTIDA_CONV",
            "VL_EMPENHADO_CONV",
            "VL_DESEMBOLSADO_CONV",
            "VL_SALDO_REMAN_TESOURO",
            "VL_SALDO_REMAN_CONVENENTE",
            "VL_RENDIMENTO_APLICACAO",
            "VL_INGRESSO_CONTRAPARTIDA",
            "VL_SALDO_CONTA",
            "VALOR_GLOBAL_ORIGINAL_CONV",
        ],
    },
    {
        "nome_tabela": "desembolso",
        "nome_csv": "siconv_desembolso.csv",
        "primary_key": ["id_desembolso"],
        "skip_rows": 0,
        "colunas": [
            "ID_DESEMBOLSO",
            "NR_CONVENIO",
            "DT_ULT_DESEMBOLSO",
            "QTD_DIAS_SEM_DESEMBOLSO",
            "DATA_DESEMBOLSO",
            "ANO_DESEMBOLSO",
            "MES_DESEMBOLSO",
            "NR_SIAFI",
            "UG_EMITENTE_DH",
            "OBSERVACAO_DH",
            "VL_DESEMBOLSADO",
        ],
    },
    {
        "nome_tabela": "desbloqueio",
        "nome_csv": "siconv_desbloqueio_cr.csv",
        # Chave composta (achada pelo repositório antigo depois da migração
        # inicial — antes considerada "sem chave natural", ver docstring).
        "primary_key": [
            "nr_convenio",
            "nr_ob",
            "data_cadastro",
            "data_envio",
            "tipo_recurso_desbloqueio",
        ],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "NR_OB",
            "DATA_CADASTRO",
            "DATA_ENVIO",
            "TIPO_RECURSO_DESBLOQUEIO",
            "VL_TOTAL_DESBLOQUEIO",
            "VL_DESBLOQUEADO",
            "VL_BLOQUEADO",
        ],
    },
    {
        "nome_tabela": "solicitacao_alteracao",
        "nome_csv": "siconv_solicitacao_alteracao.csv",
        "primary_key": ["id_solicitacao"],
        "skip_rows": 0,
        "colunas": [
            "ID_SOLICITACAO",
            "NR_CONVENIO",
            "NR_SOLICITACAO",
            "SITUACAO_SOLICITACAO",
            "OBJETO_SOLICITACAO",
            "DATA_SOLICITACAO",
        ],
    },
    {
        "nome_tabela": "termo_aditivo",
        "nome_csv": "siconv_termo_aditivo.csv",
        "primary_key": ["nr_convenio", "numero_ta"],
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "ID_SOLICITACAO",
            "NUMERO_TA",
            "TIPO_TA",
            "VL_GLOBAL_TA",
            "VL_REPASSE_TA",
            "VL_CONTRAPARTIDA_TA",
            "DT_ASSINATURA_TA",
            "DT_INICIO_TA",
            "DT_FIM_TA",
            "JUSTIFICATIVA_TA",
        ],
    },
    {
        "nome_tabela": "solicitacao_rendimento_aplicacao",
        "nome_csv": "siconv_solicitacao_rendimento_aplicacao.csv",
        "primary_key": ["id_solicitacao_rend_aplicacao"],
        "skip_rows": 0,
        "colunas": [
            "ID_SOLICITACAO_REND_APLICACAO",
            "NR_CONVENIO",
            "NR_SOLICITACAO_REND_APLICACAO",
            "STATUS_SOLICITACAO_REND_APLICACAO",
            "DATA_SOLICITACAO_REND_APLICACAO",
            "VALOR_SOLICITACAO_REND_APLICACAO",
            "VALOR_APROVADO_SOLICITACAO_REND_APLICACAO",
        ],
    },
    {
        "nome_tabela": "prorroga_oficio",
        "nome_csv": "siconv_prorroga_oficio.csv",
        # Chave composta (achada pelo repositório antigo depois da migração
        # inicial — antes considerada "sem chave natural", ver docstring).
        "primary_key": [
            "nr_convenio",
            "nr_prorroga",
            "dt_inicio_prorroga",
            "dt_fim_prorroga",
            "dt_assinatura_prorroga",
            "sit_prorroga",
        ],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "NR_PRORROGA",
            "DT_INICIO_PRORROGA",
            "DT_FIM_PRORROGA",
            "DIAS_PRORROGA",
            "DT_ASSINATURA_PRORROGA",
            "SIT_PRORROGA",
        ],
    },
    {
        "nome_tabela": "pagamento_tributo",
        "nome_csv": "siconv_pagamento_tributo.csv",
        "primary_key": ["nr_convenio", "data_tributo"],
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "DATA_TRIBUTO",
            "VL_PAG_TRIBUTOS",
        ],
    },
    {
        "nome_tabela": "pagamento",
        "nome_csv": "siconv_pagamento.csv",
        "primary_key": ["nr_mov_fin"],
        "skip_rows": 0,
        "colunas": [
            "NR_MOV_FIN",
            "NR_CONVENIO",
            "IDENTIF_FORNECEDOR",
            "NOME_FORNECEDOR",
            "TP_MOV_FINANCEIRA",
            "DATA_PAG",
            "NR_DL",
            "DESC_DL",
            "VL_PAGO",
            "ID_DL",
            "DATA_EMISSAO_DL",
        ],
    },
    {
        "nome_tabela": "licitacao",
        "nome_csv": "siconv_licitacao.csv",
        "primary_key": ["id_licitacao"],
        "skip_rows": 0,
        "colunas": [
            "ID_LICITACAO",
            "NR_CONVENIO",
            "NR_LICITACAO",
            "MODALIDADE_LICITACAO",
            "TP_PROCESSO_COMPRA",
            "TIPO_LICITACAO",
            "NR_PROCESSO_LICITACAO",
            "DATA_PUBLICACAO_LICITACAO",
            "DATA_ABERTURA_LICITACAO",
            "DATA_ENCERRAMENTO_LICITACAO",
            "DATA_HOMOLOGACAO_LICITACAO",
            "STATUS_LICITACAO",
            "SITUACAO_ACEITE_PROCESSO_EXECU",
            "SISTEMA_ORIGEM",
            "SITUACAO_SISTEMA",
            "VALOR_LICITACAO",
            "DATA_ANALISE_ACEITE",
            "DATA_ENVIO_ANALISE",
        ],
    },
    {
        "nome_tabela": "ingresso_contrapartida",
        "nome_csv": "siconv_ingresso_contrapartida.csv",
        "primary_key": ["nr_convenio", "dt_ingresso_contrapartida"],
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO",
            "DT_INGRESSO_CONTRAPARTIDA",
            "VL_INGRESSO_CONTRAPARTIDA",
        ],
    },
    {
        "nome_tabela": "empenho",
        "nome_csv": "siconv_empenho.csv",
        # Chave composta (achada pelo repositório antigo depois da migração
        # inicial — antes considerada "sem chave natural", ver docstring).
        "primary_key": ["id_empenho", "nr_empenho", "tipo_nota"],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "ID_EMPENHO",
            "NR_CONVENIO",
            "NR_EMPENHO",
            "TIPO_NOTA",
            "DESC_TIPO_NOTA",
            "DATA_EMISSAO",
            "COD_SITUACAO_EMPENHO",
            "DESC_SITUACAO_EMPENHO",
            "UG_EMITENTE",
            "UG_RESPONSAVEL",
            "FONTE_RECURSO",
            "NATUREZA_DESPESA",
            "PLANO_INTERNO",
            "PTRES",
            "VALOR_EMPENHO",
            "RESULTADO_PRIMARIO",
            "OBSERVACAO_EMPENHO",
            "DESCRICAO_EMENDA_SIAFI",
        ],
    },
    {
        "nome_tabela": "historico_situacao",
        "nome_csv": "siconv_historico_situacao.csv",
        # Chave composta (achada pelo repositório antigo depois da migração
        # inicial — antes considerada "sem chave natural", ver docstring).
        "primary_key": [
            "id_proposta",
            "nr_convenio",
            "dia_historico_sit",
            "historico_sit",
            "dias_historico_sit",
            "cod_historico_sit",
        ],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA",
            "NR_CONVENIO",
            "DIA_HISTORICO_SIT",
            "HISTORICO_SIT",
            "DIAS_HISTORICO_SIT",
            "COD_HISTORICO_SIT",
        ],
    },
    {
        "nome_tabela": "cronograma_desembolso",
        "nome_csv": "siconv_cronograma_desembolso.csv",
        "primary_key": ["id_proposta", "nr_convenio", "nr_parcela_crono_desembolso"],
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA",
            "NR_CONVENIO",
            "NR_PARCELA_CRONO_DESEMBOLSO",
            "MES_CRONO_DESEMBOLSO",
            "ANO_CRONO_DESEMBOLSO",
            "TIPO_RESP_CRONO_DESEMBOLSO",
            "VALOR_PARCELA_CRONO_DESEMBOLSO",
        ],
    },
    {
        "nome_tabela": "meta_crono_fisico",
        "nome_csv": "siconv_meta_crono_fisico.csv",
        "primary_key": ["id_meta"],
        "skip_rows": 0,
        "colunas": [
            "ID_META",
            "ID_PROPOSTA",
            "NR_CONVENIO",
            "COD_PROGRAMA",
            "NOME_PROGRAMA",
            "NR_META",
            "TIPO_META",
            "DESC_META",
            "DATA_INICIO_META",
            "DATA_FIM_META",
            "UF_META",
            "MUNICIPIO_META",
            "ENDERECO_META",
            "CEP_META",
            "QTD_META",
            "UND_FORNECIMENTO_META",
            "VL_META",
        ],
    },
]
