name: Update Changelog

on:
  pull_request:
    types: [closed]
    branches: [main, master]

permissions:
  contents: write
  pull-requests: read

jobs:
  build-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build changelog section from merged PRs
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/release-changelog-builder-config.json
          toTag: ${{ github.sha }}
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure changelog directory exists
        run: mkdir -p docs/documentacao

      - name: Compose new section
        run: |
          TODAY=$(date -u +'%Y-%m-%d')
          {
            echo "## $TODAY"
            echo
            echo "${{ steps.changelog.outputs.changelog }}"
            echo
          } > .new_section.md

      - name: Create header if file doesn't exist
        run: |
          FILE="docs/documentacao/CHANGELOG.md"
          if [ ! -f "$FILE" ]; then
            cat > "$FILE" <<'HDR'
# Changelog
This file contains a summary of changes to the GovHub codebase from PR #2 onwards.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),

## Recent Merged Pull Requests
HDR
            echo >> "$FILE"
          fi

      - name: Prepend new section after header
        run: |
          FILE="docs/documentacao/CHANGELOG.md"
          TMP=$(mktemp)
          cp "$FILE" "$TMP"

          # If the "Recent Merged Pull Requests" header exists, insert right after it.
          if grep -nq "^## Recent Merged Pull Requests" "$FILE"; then
            LINE=$(grep -n '^## Recent Merged Pull Requests' "$FILE" | head -1 | cut -d: -f1)
            head -n "$LINE" "$FILE" > .head.md
            tail -n +$((LINE+1)) "$TMP" > .body.md
            cat .head.md .new_section.md .body.md > "$FILE"
          else
            # Otherwise, just prepend at the very top (after any existing header).
            cat .new_section.md "$TMP" > "$FILE"
          fi

      - name: Create PR with changelog update
        uses: peter-evans/create-pull-request@v6
        with:
          title: "docs: update changelog from PR #${{ github.event.pull_request.number }}"
          commit-message: "docs(changelog): include PR #${{ github.event.pull_request.number }}"
          body: "Automated update of docs/documentacao/CHANGELOG.md from labels on merged PRs."
          branch: chore/update-changelog-${{ github.run_id }}
          labels: documentation
